"""add shots table

Revision ID: 8191f7b2a8cf
Revises: dcd0df2f5015
Create Date: 2026-09-10 17:13:02.877440

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8191f7b2a8cf'
down_revision: str | Sequence[str] | None = 'dcd0df2f5015'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bean_id', sa.Integer(), nullable=False),
    sa.Column('dose', sa.Float(), nullable=False),
    sa.Column('grind_size', sa.Float(), nullable=False),
    sa.Column('grind_time', sa.Float(), nullable=False),
    sa.Column('shot_yield', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shots')
    # ### end Alembic commands ###
